import { ShoppingCartIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import { useRouter } from "next/router";
import { ReactElement, useContext } from "react";
import CartOverlay from "../../components/Cart/CartOverlay";
import Layout from "../../components/common/Layout";
import { UserContext } from "../../providers/UserContext";
import { NextPageWithLayout } from "../_app";

const product = {
  id: 3,
  name: "T-Shirt 3",
  description: "T-Shirt",
  price: 15,
  image:
    "https://media.istockphoto.com/id/1311574382/photo/blue-t-shirt-isolated-on-white-background.jpg?b=1&s=170667a&w=0&k=20&c=3aHoYgSUnlX8MaEtQ__mO7mInI_kCst10kfBYmpJf48=",
};

const Page = () => {
  //   const { query } = useRouter();
  //   const productId = query.productId;
  //   const { user, isLoading, isAuthenticated, refetch, setUser } =
  //     useContext(UserContext);
  //   async function handleAddToCart() {
  //     if (!user?.cart) {
  //       // if successfully created user, create cart for user
  //       console.log("creating Cart for user");
  //       if (user?.["@id"]) {
  //         createCart({ relatedUser: user["@id"] }).then((_cart) =>
  //           updateCart({
  //             productIris: [
  //               ...(_cart.products.map((product) => product["@id"]) as string[]),
  //               `/api/products/${productId}`,
  //             ],
  //             cartId: _cart["@id"],
  //           })
  //         );
  //       }
  //     } else {
  //       let cart = null;
  //       if (!isLoading && isAuthenticated && user?.cart) {
  //         if (!cart) {
  //           cart = await getCart(user?.cart);
  //         }
  //         updateCart({
  //           productIris: [
  //             ...(cart.products.map((product) => product["@id"]) as string[]),
  //             `/api/products/${productId}`,
  //           ],
  //           cartId: user?.cart,
  //         });
  //       }
  //     }
  //   }
  //   return (
  //     <div>
  //       <Head>
  //         <title>Pay</title>
  //         <meta name="description" content="Generated by create next app" />
  //         <meta name="viewport" content="width=device-width, initial-scale=1" />
  //         <link rel="icon" href="/favicon.ico" />
  //       </Head>
  //       <div className="md:flex md:justify-center md:items-center md:h-[calc(100vh_-_200px)]">
  //         <div className="flex flex-col gap-8 md:flex-row md:justify-center md:gap-32 md:max-w-screen-xl md:items-center md:px-8 md:whitespace-nowrap">
  //           <img
  //             className="aspect-square w-full object-cover rounded-lg"
  //             src={product.image}
  //             alt={product.name}
  //           />
  //           <div className="flex flex-col gap-8">
  //             <h1 className="font-bold text-4xl">{product.name}</h1>
  //             <p className="text-gray-400 whitespace-pre-wrap">
  //               {product.description}
  //             </p>
  //             <p className="font-bold text-2xl">{product.price + " €"}</p>
  //             <button
  //               onClick={handleAddToCart}
  //               className="space-x-6 w-full rounded-lg bg-orange-500 py-5 text-white font-bold flex items-center justify-center shadow-2xl shadow-orange-200 md:w-fit md:px-16"
  //             >
  //               <ShoppingCartIcon className="w-5" />
  //               <p>Add to cart</p>
  //             </button>
  //           </div>
  //         </div>
  //       </div>
  //     </div>
  //   );
};

// Page.getLayout = function getLayout(page: ReactElement) {
//   return (
//     <Layout>
//       {page}
//       {/* <CartOverlay /> */}
//     </Layout>
//   );
// };

export default Page;
