import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { ReactElement } from "react";
import Layout from "../components/common/Layout";
import { useUser } from "../helpers/UserLogic/useUser";
import { UserContext } from "../providers/UserContext";
import { NextPageWithLayout } from "./_app";
import Typed from "react-typed";
import OfferSection from "../components/LandingPage/OfferSection";
import { FAQSection } from "../components/LandingPage/FAQSection";
import FeatureSection from "../components/LandingPage/FeatureSection";
import Toast from "../components/Toasts/Toast";

const Page: NextPageWithLayout = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Smart Shirt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto px-6 pt-32 xl:container md:px-12 md:py-12 xl:mt-20">
        <div
          aria-hidden="true"
          className="absolute inset-0 my-auto h-32 w-96 rotate-45 bg-gradient-to-r from-secondary to-tertiary opacity-50 blur-3xl dark:opacity-20"
        ></div>
        <div className="relative lg:flex lg:items-center lg:gap-12">
          <div className="text-center sm:mx-auto sm:w-10/12 md:mt-12 md:w-2/3 lg:mr-auto lg:mt-0 lg:w-6/12 lg:text-left">
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white md:text-6xl lg:text-5xl xl:text-6xl">
              Create your own unique T-Shirt design{" "}
              <span className="text-secondary dark:text-secondary">
                super fast
              </span>
            </h1>
            <p className="mt-8 text-gray-600 dark:text-gray-300">
              With our text to image generator you can create your own unique
              T-Shirt design in seconds. The times of hiring a designer are
              over. Now you can do it yourself.
            </p>
            <div>
              <div className="mt-12 w-full">
                <div className="flex flex-col gap-4 sm:flex-row">
                  <button
                    type="button"
                    title="Start buying"
                    className="w-full rounded-xl bg-secondary px-6 py-3 text-center transition hover:bg-secondaryLight active:bg-secondary/90 sm:w-max"
                  >
                    <span className="block font-semibold text-white">
                      Create your design now
                    </span>
                  </button>
                  <button
                    type="button"
                    title="Start buying"
                    className="w-full rounded-xl px-6 py-3 text-center transition focus:bg-green-100 active:bg-green-200 dark:focus:bg-gray-800 dark:active:bg-green-900 sm:w-max"
                  >
                    <div className="flex justify-center">
                      <span className="block font-semibold text-primary dark:text-secondaryLight">
                        Discover our designs
                      </span>
                    </div>
                  </button>
                </div>
              </div>
            </div>
            <div className="mt-12 flex justify-between gap-6 grayscale dark:grayscale-0 lg:gap-12">
              <img
                src="./images/clients/airbnb.svg"
                className="h-8 w-auto sm:h-10 lg:h-12"
                alt=""
              />
              <img
                src="./images/clients/ge.svg"
                className="h-8 w-auto sm:h-10 lg:h-12"
                alt=""
              />
              <img
                src="./images/clients/coty.svg"
                className="h-8 w-auto sm:h-10 lg:h-12"
                alt=""
              />
              <img
                src="./images/clients/microsoft.svg"
                className="h-8 w-auto sm:h-10 lg:h-12"
                alt=""
              />
            </div>
          </div>
          <div className="relative w-full overflow-hidden lg:-mr-16 lg:w-7/12">
            <Image
              src="/attractive-woman.png"
              alt="project illustration"
              className="h-max w-full"
              height={1000}
              width={1000}
            />
            <div className="absolute right-5 top-36 drop-shadow-2xl">
              <Typed
                strings={[
                  "Create a cute, realistic image of a lively fox in a natural setting with warm lighting.",
                ]}
                className="block w-full max-w-xs rounded-lg bg-lightGray p-5 text-sm text-primary focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                typeSpeed={40}
                startDelay={2000}
              />
            </div>
          </div>
        </div>
      </div>
      <FeatureSection />
      <OfferSection />
      <FAQSection />
    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Page;
